Feature/address value renderers
nmshd/app pull request #171
Opened 2024-03-22 15:12 UTC by nicole-eb

2024-04-02 06:34 UTC, jkoenig134 commented on packages/value_renderer/lib/src/renderers/address/street_address.dart
> +  }
this can be inline. and please use the early return pattern. Please look again over the other renderers and apply the same things.

2024-04-02 09:46 UTC, jkoenig134 commented on packages/value_renderer/lib/src/renderers/address/street_address.dart
> +  }
you ignored half of the comment ;) why is this a method when it isn't used in more than one place? Additionally the ternary can also be simplified as an early return

2024-04-02 11:34 UTC, jkoenig134 commented on packages/value_renderer/lib/src/inputs/text_input.dart
> +  final AutovalidateMode? autovalidateMode;
why is this optional?

2024-04-02 11:34 UTC, jkoenig134 commented on packages/value_renderer/lib/src/inputs/dropdown_select_input.dart
> +  final AutovalidateMode? autovalidateMode;
why is this optional?

2024-04-02 11:35 UTC, jkoenig134 commented on packages/value_renderer/lib/src/renderers/address/delivery_box_address.dart
> +  bool get _containsAllRequiredValues => _requiredValues.every((element) => _valueMap.containsKey(element));
_containsAllRequiredValues can also be removed in all widgets (like _validateForm)

2024-04-02 11:41 UTC, jkoenig134 commented on packages/value_renderer/lib/src/renderers/complex.dart
> +    if (initialValue is BirthDateAttributeValue || valueType == 'BirthDate') {
I'd vote for removing all `initialValue is` checks as I don't understand why we need that.

2024-04-02 11:59 UTC, nicole-eb commented on packages/value_renderer/lib/src/renderers/address/delivery_box_address.dart
> +  bool get _containsAllRequiredValues => _requiredValues.every((element) => _valueMap.containsKey(element));
should every required field show an error message before the user interacts with the form?

2024-04-02 12:01 UTC, jkoenig134 commented on packages/value_renderer/lib/src/renderers/address/delivery_box_address.dart
> +  bool get _containsAllRequiredValues => _requiredValues.every((element) => _valueMap.containsKey(element));
nope, but I don't know why this is important here? Just inline the code.

2024-04-02 12:05 UTC, nicole-eb commented on packages/value_renderer/lib/src/renderers/address/delivery_box_address.dart
> +  bool get _containsAllRequiredValues => _requiredValues.every((element) => _valueMap.containsKey(element));
it was just a general question

2024-04-02 12:06 UTC, jkoenig134 commented on packages/value_renderer/lib/src/renderers/address/delivery_box_address.dart
> +  bool get _containsAllRequiredValues => _requiredValues.every((element) => _valueMap.containsKey(element));
IC

2024-04-02 12:33 UTC, jkoenig134 commented on packages/value_renderer/lib/src/renderers/address/delivery_box_address.dart
> +      _valueMap.remove(key);
why don't remove the value from the map if it's not required? IMO we should always do that

2024-04-03 09:20 UTC, jkoenig134 requested changes
only two small things

2024-04-03 09:20 UTC, jkoenig134 commented on packages/value_renderer/lib/src/renderers/address/delivery_box_address.dart
> +import '/value_renderer.dart';
this import is huge (same for other files)

2024-04-03 09:20 UTC, jkoenig134 commented on packages/value_renderer/lib/src/renderers/address/delivery_box_address.dart
> +import './extensions.dart';
```suggestion
import 'extensions.dart';
```

same for other files

2024-04-03 10:26 UTC, jkoenig134 approved these changes

2024-04-03 11:11 UTC, merged