Feature/Update Runtime for Attribute deletion
nmshd/app pull request #185
Opened 2024-04-24 14:45 UTC by Milena-Czierlinski

2024-04-24 14:52 UTC, Milena-Czierlinski commented on packages/enmeshed_runtime_bridge/lib/src/services/facades/consumption/attributes_facade.dart
> +    return Result.fromJson(json, (value) => value);
I reckon this is not doing the job. However, the corresponding test seems to fail already before. But I'm not sure, since my initial breakpoint isn't reached.

2024-04-25 13:49 UTC, jkoenig134 commented on packages/enmeshed_runtime_bridge/lib/src/services/facades/consumption/attributes_facade.dart
> +import 'dart:ffi';
ehm, why ffi?

2024-04-25 13:52 UTC, jkoenig134 commented on packages/enmeshed_types/lib/src/contents/notification_item/third_party_owned_relationship_attribute_deleted_by_peer_notification_item.dart
> +  Map<String, dynamic> toJson() => _$ThirdPartyOwnedRelationshipAttributeDeletedByPeerNotificationItemToJson(this);
`@type` is missing

2024-04-25 13:59 UTC, jkoenig134 requested changes

2024-04-25 13:59 UTC, jkoenig134 commented on packages/enmeshed_types/lib/src/contents/notification_item/peer_shared_attribute_succeeded_notification_item.dart
> +  Map<String, dynamic> toJson() => _$PeerSharedAttributeSucceededNotificationItemToJson(this);
`@type` is missing

2024-04-25 13:59 UTC, jkoenig134 commented on packages/enmeshed_types/lib/src/contents/notification_item/peer_shared_attribute_deleted_by_peer_notification_item.dart
> +  Map<String, dynamic> toJson() => _$PeerSharedAttributeDeletedByPeerNotificationItemToJson(this);
`@type` is missing

2024-04-25 13:59 UTC, jkoenig134 commented on packages/enmeshed_types/lib/src/dtos/local_attribute.dart
>    }
just remove toString pls

2024-04-25 13:59 UTC, jkoenig134 commented on packages/enmeshed_types/lib/src/dtos/local_attribute_deletion_info.dart
> +enum DeletionStatus { toBeDeleted, toBeDeletedByPeer, deletedByPeer, deletedByOwner }
does this work? The statuses in the runtime are capitalized

2024-04-25 13:59 UTC, jkoenig134 commented on packages/enmeshed_types/lib/src/responses/delete_attribute_and_notify.dart
one class per file pls

2024-04-25 15:10 UTC, Milena-Czierlinski commented on packages/enmeshed_types/lib/src/contents/notification_item/peer_shared_attribute_deleted_by_peer_notification_item.dart
> +  Map<String, dynamic> toJson() => _$PeerSharedAttributeDeletedByPeerNotificationItemToJson(this);
Can you please be more precise, how this would need to be implemented? The only existing NotificationItem doesn't have `@type` neither. The RequestItems do, however, there no file is generated. So, does this need to be done here manually or should the generation take care of this?

2024-04-25 15:12 UTC, jkoenig134 commented on packages/enmeshed_types/lib/src/contents/notification_item/peer_shared_attribute_deleted_by_peer_notification_item.dart
> +  Map<String, dynamic> toJson() => _$PeerSharedAttributeDeletedByPeerNotificationItemToJson(this);
I told you how to do this in the onboarding that's why I wasn't more precise.

In this case you can do 
```dart
@override
  Map<String, dynamic> toJson() => {
        ..._$PeerSharedAttributeDeletedByPeerNotificationItemToJson(this),
        '@type': 'PeerSharedAttributeDeletedByPeerNotificationItem',
      };
```

2024-04-25 15:13 UTC, jkoenig134 commented on packages/enmeshed_types/lib/src/contents/notification_item/peer_shared_attribute_deleted_by_peer_notification_item.dart
> +  Map<String, dynamic> toJson() => _$PeerSharedAttributeDeletedByPeerNotificationItemToJson(this);
> The only existing NotificationItem doesn't have @type neither. 

I think that's wrong too.

2024-04-25 15:16 UTC, jkoenig134 commented on packages/enmeshed_runtime_bridge/lib/src/services/facades/consumption/attributes_facade.dart
> +import 'dart:ffi';
I see. You are using a wrong type here, I'll comment how to handle it instead.

2024-04-25 15:17 UTC, jkoenig134 commented on packages/enmeshed_runtime_bridge/lib/src/services/facades/consumption/attributes_facade.dart
> +    return Result.failure(RuntimeError(message: message, code: code));
```suggestion
    final json = result.valueToMap();
    return Result.fromJson(json, (_) {});
```

2024-04-25 15:42 UTC, Milena-Czierlinski commented on packages/enmeshed_runtime_bridge/lib/src/services/facades/consumption/attributes_facade.dart
> +    return Result.failure(RuntimeError(message: message, code: code));
This is not working.
```
Null check operator used on a null value
```
I think the value of the returned result is null, such that in `result.dart` it tries to throw an error, but non exists.

2024-04-25 17:01 UTC, jkoenig134 commented on packages/enmeshed_runtime_bridge/lib/src/services/facades/consumption/attributes_facade.dart
> +    return Result.failure(RuntimeError(message: message, code: code));
argh, that's ugly..

2024-04-25 17:02 UTC, jkoenig134 commented on packages/enmeshed_runtime_bridge/lib/src/services/facades/consumption/attributes_facade.dart
> +    return Result.failure(RuntimeError(message: message, code: code));
`deleteDevice` in `packages/enmeshed_runtime_bridge/lib/src/services/facades/transport/devices_facade.dart` uses `Future<Result<bool>>` because of this..

2024-04-25 17:27 UTC, jkoenig134 commented on packages/enmeshed_types/lib/src/dtos/local_attribute.dart
>    }
compiler or runtime?

2024-04-25 17:30 UTC, jkoenig134 commented on packages/enmeshed_types/lib/src/dtos/local_attribute.dart
>    }
(for me it works ...)

2024-04-26 12:54 UTC, jkoenig134 commented on packages/enmeshed_runtime_bridge/integration_test/services/facades/consumption/attributes_facade_test.dart
> +      expect(successfulDeletionResult, isSuccessful<VoidResult>());
```suggestion
      expect(successfulDeletionResult, isSuccessful());
```

I think it should be like that. Same with all other occurences

2024-04-29 09:43 UTC, jkoenig134 approved these changes
LGTM. Try to re-run the tests, seems like the backbone does sth strange.

2024-04-29 13:28 UTC, merged