Chore/Remove relationship changes, add relationship termination,reactivation
nmshd/app pull request #216
Opened 2024-07-01 08:06 UTC by Magnus-Kuhn

2024-07-10 15:39 UTC, britsta commented on packages/enmeshed_types/lib/src/contents/relationship_creation_content/relationship_creation_content.dart
> +class ArbitraryRelationshipCreationContent extends RelationshipCreationContent with MapMixin<String, dynamic>, ArbitraryJSON {
This isn't the `ArbitraryRelationshipCreationContent`, which will only be introduced by the (currently not yet merged) PR https://github.com/nmshd/runtime/pull/170, right?

2024-07-10 15:39 UTC, britsta commented on packages/enmeshed_types/lib/src/dtos/relationship.dart
> +class RelationshipAuditLogEntryDTO extends Equatable {
`RelationshipAuditLogDTO` is missing.

2024-07-10 16:03 UTC, britsta commented on .dev/compose.backbone.env
> +BACKBONE_VERSION=6.2.0
Okay, https://github.com/nmshd/runtime/pull/125/files#diff-0cff58168f80528b3a79e26b82851cdd8b3b24b6d8ba5ce750a01b715012e4f1 is merged now, so this comment is a little bit outdated :D As this PR did not take the changes from `5.0.0-alpha.4` to `5.0.0-alpha.6` (removal of `mustBeAccepted` property of RequestItemGroup and decomposition of Relationships) into account, I still think the `BACKBONE_VERSION` should be changed to `6.1.0` here and the Runtime version in the `package.json` from `5.0.0-alpha.5` to `5.0.0-alpha.4`.

2024-07-11 05:53 UTC, jkoenig134 commented on packages/enmeshed_runtime_bridge/integration_test/services/facades/transport/account_facade_test.dart
> -      expect(identityInfoResult.value.address.length, lessThanOrEqualTo(36));
I think we should expect addresses completely different. For example splitting it at : and only looking at the last (address) part.

2024-07-11 06:28 UTC, Magnus-Kuhn commented on packages/enmeshed_runtime_bridge/integration_test/services/facades/transport/messages_facade_test.dart
> +    const fakeAddress = 'did:e:prod.enmeshed.eu:dids:fef1992c5e529adc413288';
I guess the cat is out of the bag there (why did I do this when it wasn't necessary ???)

2024-07-11 06:31 UTC, Magnus-Kuhn commented on packages/enmeshed_runtime_bridge/integration_test/services/facades/transport/messages_facade_test.dart
> +    const fakeAddress = 'did:e:prod.enmeshed.eu:dids:fef1992c5e529adc413288';
I'll include the runtime change in my next PR

2024-07-11 07:42 UTC, Magnus-Kuhn commented on packages/enmeshed_types/lib/src/contents/relationship_creation_content/relationship_creation_content.dart
> +class ArbitraryRelationshipCreationContent extends RelationshipCreationContent with MapMixin<String, dynamic>, ArbitraryJSON {
right, arbitraryContents are also used elsewhere

2024-07-11 07:43 UTC, Magnus-Kuhn commented on packages/enmeshed_types/test/contents/token_content/token_content_device_shared_secret_test.dart
removed it

2024-07-11 07:58 UTC, Magnus-Kuhn commented on packages/enmeshed_runtime_bridge/integration_test/services/facades/consumption/attributes_facade_test.dart
I'd like to remark that I hate facades exposing use cases that are only supposed to be used through the request module for additional implementation effort.

2024-07-11 08:06 UTC, britsta commented on packages/enmeshed_runtime_bridge/integration_test/services/facades/consumption/attributes_facade_test.dart
As I understand it, the use cases should also be able to be executed by Integrators of Connectors if they do not want to use the Request module and want to implement the processes themselves instead, even though the Request module will probably be active most of the time in practice. However, I do not know exactly whether it makes sense to transfer such use cases from a facade of the Runtime to a facade of the App.

2024-07-11 08:17 UTC, jkoenig134 commented on packages/enmeshed_runtime_bridge/integration_test/services/facades/consumption/attributes_facade_test.dart
Please do not add methods we don't need! We should not use `deleteSharedAttributesForRejectedOrRevokedRelationship` and don't need to expose this here!

2024-07-11 08:41 UTC, Magnus-Kuhn commented on packages/enmeshed_runtime_bridge/integration_test/services/facades/transport/account_facade_test.dart
> -      expect(identityInfoResult.value.address.length, lessThanOrEqualTo(36));
I'm going full regex match

2024-07-11 08:48 UTC, Magnus-Kuhn commented on packages/enmeshed_types/lib/src/dtos/relationship_change.dart
I'm not sure about the end result with the texts - would the app devs like us to leave them some TODOs where they need to add something?

2024-07-11 09:09 UTC, Magnus-Kuhn commented on packages/enmeshed_types/lib/src/dtos/relationship.dart
> +class RelationshipAuditLogEntryDTO extends Equatable {
This setup with classes doesn't allow an unnamed property List<AuditLogEntry>. If consistency is needed, I'm happy to ditch it in the runtime.

2024-07-11 09:18 UTC, jkoenig134 commented on packages/enmeshed_types/lib/src/dtos/relationship.dart
> +class RelationshipAuditLogEntryDTO extends Equatable {
`RelationshipAuditLogDTO` ist just a list of `RelationshipAuditLogEntryDTO` and don't has to have an equivalent in this coding

2024-07-12 12:07 UTC, jkoenig134 requested changes

2024-07-12 12:07 UTC, jkoenig134 commented on packages/enmeshed_types/lib/src/contents/attribute_query/third_party_relationship_attribute_query.dart
>  class ThirdPartyRelationshipAttributeQuery extends AttributeQuery {
plase make this JsonSerializable again

2024-07-12 12:07 UTC, jkoenig134 commented on packages/enmeshed_types/lib/src/contents/relationship_creation_content/relationship_creation_content_containing_response.dart
> +class RelationshipCreationContentContainingResponse extends RelationshipCreationContent {
RelationshipCreationContent

2024-07-12 12:07 UTC, jkoenig134 commented on packages/enmeshed_types/lib/src/contents/relationship_creation_content/relationship_creation_content.dart
> +abstract class RelationshipCreationContent extends Equatable {
```suggestion
abstract class RelationshipCreationContentDerivation extends Equatable {
```

2024-07-12 12:15 UTC, jkoenig134 commented on packages/enmeshed_types/lib/src/dtos/relationship_change.dart
@britsta please keep that in mind for the final review of the v5 branch.

2024-07-12 13:40 UTC, jkoenig134 approved these changes

2024-07-12 13:44 UTC, jkoenig134 approved these changes

2024-07-12 13:47 UTC, merged