Feature/Add CanCreateRelationship use case
nmshd/app pull request #313
Opened 2024-10-28 15:49 UTC by Milena-Czierlinski

and 
- add `thirdPartyAddress` to LocalAttributeShareInfo for OwnRelationshipAttributes and PeerRelationshipAttributes
- adjust ThirdPartyRelationshipAttribute nomenclature

2024-10-30 15:42 UTC, jkoenig134 commented
Could you upgrade this to runtime 6.6.0? And maybe update the PR name accordingly :D

2024-10-30 15:46 UTC, Milena-Czierlinski commented
I suggest to do this in a separate PR to keep them manageable.

2024-10-30 15:48 UTC, jkoenig134 requested changes
I have now reviewed the first test-file and see that this PR needs a proper self-review :)

2024-10-30 15:48 UTC, jkoenig134 commented on packages/enmeshed_runtime_bridge/android/gradle/wrapper/gradle-wrapper.properties
could you please undo this?

2024-10-30 15:48 UTC, jkoenig134 commented on packages/connector_sdk/lib/src/endpoints/relationships_endpoint.dart
> +          {required String templateId, required Map<String, dynamic> creationContent}) =>
```suggestion
          {required String templateId, required Map<String, dynamic> creationContent,}) =>
```

2024-10-30 15:48 UTC, jkoenig134 commented on packages/enmeshed_runtime_bridge/integration_test/services/facades/consumption/attributes_facade_test.dart
>            sender, recipient, senderAddress, recipientAddress, thirdPartyAddress, requestItem, senderOwnSharedRelationshipAttribute.id, eventBus);
there's a trailing comma missing

2024-10-30 15:48 UTC, jkoenig134 commented on packages/enmeshed_runtime_bridge/integration_test/services/facades/consumption/attributes_facade_test.dart
> +          .deleteThirdPartyRelationshipAttributeAndNotifyPeer(attributeId: senderThirdPartyRelationshipAttribute.id);
trailing comma

2024-10-30 15:48 UTC, jkoenig134 commented on packages/enmeshed_runtime_bridge/integration_test/services/facades/consumption/attributes_facade_test.dart
> +          (await sender.consumptionServices.attributes.getAttribute(attributeId: thirdPartyRelationshipAttribute.id)).value;
trailing comma

2024-10-30 15:48 UTC, jkoenig134 commented on packages/enmeshed_runtime_bridge/integration_test/services/facades/consumption/attributes_facade_test.dart
> +          (await sender.consumptionServices.attributes.getAttribute(attributeId: senderThirdPartyRelationshipAttribute.id)).value;
trailing comma

2024-10-30 15:48 UTC, jkoenig134 commented on packages/enmeshed_runtime_bridge/integration_test/services/facades/consumption/attributes_facade_test.dart
> +          .deleteThirdPartyRelationshipAttributeAndNotifyPeer(attributeId: recipientThirdPartyRelationshipAttribute.id);
trailing comma

2024-10-30 15:48 UTC, jkoenig134 commented on packages/enmeshed_runtime_bridge/integration_test/services/facades/consumption/attributes_facade_test.dart
> +          .deleteThirdPartyRelationshipAttributeAndNotifyPeer(attributeId: senderThirdPartyRelationshipAttribute.id);
trailing comma

2024-10-30 15:48 UTC, jkoenig134 commented on packages/enmeshed_runtime_bridge/integration_test/services/facades/consumption/attributes_facade_test.dart
> +          eventTargetAddress: recipientAddress, predicate: (e) => e.data.id == senderThirdPartyRelationshipAttribute.id);
trailing comma

2024-10-30 15:48 UTC, jkoenig134 commented on packages/enmeshed_runtime_bridge/integration_test/services/facades/consumption/attributes_facade_test.dart
> +          (await recipient.consumptionServices.attributes.getAttribute(attributeId: senderThirdPartyRelationshipAttribute.id)).value;
trailing comma

2024-10-30 15:48 UTC, jkoenig134 commented on packages/enmeshed_runtime_bridge/integration_test/services/facades/consumption/attributes_facade_test.dart
> +          (await sender.consumptionServices.attributes.getAttribute(attributeId: thirdPartyRelationshipAttribute.id)).value;
trailing comma

2024-10-30 15:48 UTC, jkoenig134 commented on packages/enmeshed_runtime_bridge/integration_test/services/facades/consumption/attributes_facade_test.dart
> +          .deleteThirdPartyRelationshipAttributeAndNotifyPeer(attributeId: senderThirdPartyRelationshipAttribute.id);
trailing comma

2024-10-30 15:48 UTC, jkoenig134 commented
> I suggest to do this in a separate PR to keep them manageable.

check :)

2024-10-30 15:51 UTC, jkoenig134 commented
But please rename the pr to `Feature/Update runtime to 6.5.0` or sth similar.

2024-10-30 15:59 UTC, britsta commented on packages/enmeshed_runtime_bridge/android/gradle/wrapper/gradle-wrapper.properties
Done :) Such changes are frequently made locally when I execute certain commands for updates. Are there cases where we don't have to discard them?

2024-10-30 16:01 UTC, jkoenig134 commented on packages/enmeshed_runtime_bridge/android/gradle/wrapper/gradle-wrapper.properties
please collect them, but this should not be committed to PRs like this.

2024-10-30 16:03 UTC, britsta commented on packages/enmeshed_runtime_bridge/android/gradle/wrapper/gradle-wrapper.properties
So collect them in a separate chore PR and merge them all together into main?

2024-10-30 16:05 UTC, jkoenig134 commented on packages/enmeshed_runtime_bridge/android/gradle/wrapper/gradle-wrapper.properties
yep

2024-10-30 16:06 UTC, jkoenig134 commented on packages/enmeshed_runtime_bridge/integration_test/services/facades/consumption/attributes_facade_test.dart
> +          (await sender.consumptionServices.attributes.getAttribute(attributeId: thirdPartyRelationshipAttribute.id)).value;
it's WAY better.

2024-10-30 16:20 UTC, jkoenig134 commented on packages/enmeshed_runtime_bridge/integration_test/services/facades/transport/relationships_facade_test.dart
> +          'The Identity who created the RelationshipTemplate is currently in the process of deleting itself. Thus, it is not possible to establish a Relationship to it.');
two trailing commas

2024-10-30 16:23 UTC, jkoenig134 commented on packages/enmeshed_types/lib/src/responses/can_create_relationship_response.dart
> +  CanCreateRelationshipSuccessResponse({super.isSuccess = true});
please put this to an initializer for isSuccess https://dart.dev/language/constructors#use-an-initializer-list

same for false below

2024-10-31 09:48 UTC, britsta commented on packages/enmeshed_runtime_bridge/integration_test/services/facades/transport/relationships_facade_test.dart
> +          'The Identity who created the RelationshipTemplate is currently in the process of deleting itself. Thus, it is not possible to establish a Relationship to it.');
Done! Do you recommend to put trailing commas here because of the line breaks caused by long lines?

2024-10-31 09:50 UTC, jkoenig134 commented on packages/enmeshed_runtime_bridge/integration_test/services/facades/transport/relationships_facade_test.dart
> +          'The Identity who created the RelationshipTemplate is currently in the process of deleting itself. Thus, it is not possible to establish a Relationship to it.');
hm, don't you see the huge difference in readablity from before and after?

2024-10-31 09:56 UTC, jkoenig134 approved these changes

2024-10-31 09:56 UTC, britsta commented on packages/enmeshed_runtime_bridge/integration_test/services/facades/transport/relationships_facade_test.dart
> +          'The Identity who created the RelationshipTemplate is currently in the process of deleting itself. Thus, it is not possible to establish a Relationship to it.');
I prefer not to add such formatting according to personal opinion about readability, but according to fixed rules, if there are any (for example, in the case of a line break) 🤔

2024-10-31 09:57 UTC, jkoenig134 commented on packages/enmeshed_runtime_bridge/integration_test/services/facades/transport/relationships_facade_test.dart
> +          'The Identity who created the RelationshipTemplate is currently in the process of deleting itself. Thus, it is not possible to establish a Relationship to it.');
yeah, it is - I can show you.

2024-10-31 10:32 UTC, merged