Feature/generate recovery kit as pdf
nmshd/app pull request #335
Opened 2024-11-26 11:03 UTC by aince42

2024-11-26 11:54 UTC, nicole-eb requested changes

2024-11-26 11:54 UTC, nicole-eb commented on packages/identity_recovery_kit/README.md
> +<!--
I think you could shortly summarize what this package is, like the readme of the other packages

2024-11-26 11:54 UTC, nicole-eb commented on packages/identity_recovery_kit/pubspec.yaml
> +  # https://flutter.dev/to/font-from-package
Can be removed

2024-11-26 11:54 UTC, nicole-eb commented on packages/identity_recovery_kit/LICENSE
> +TODO: Add your license here.
Needs to be updated

2024-11-26 12:14 UTC, jkoenig134 requested changes

2024-11-26 12:14 UTC, jkoenig134 commented on packages/identity_recovery_kit/CHANGELOG.md
delete this file.

2024-11-26 12:14 UTC, jkoenig134 commented on packages/identity_recovery_kit/analysis_options.yaml
see other packages and examples on how to setup lints.

2024-11-26 12:14 UTC, jkoenig134 commented on packages/identity_recovery_kit/example/README.md
> +samples, guidance on mobile development, and a full API reference.
why all the boilerplate stuff, please don't check in everything recklessly.

2024-11-26 12:14 UTC, jkoenig134 commented on packages/identity_recovery_kit/example/analysis_options.yaml
wrong lint file.

2024-11-26 12:14 UTC, jkoenig134 commented on patches.md
OMG, check what you commit.

2024-11-26 12:14 UTC, jkoenig134 commented on packages/identity_recovery_kit/example/pubspec.yaml
> +  # see https://flutter.dev/to/font-from-package
remove all the comments, also above.

2024-11-26 12:14 UTC, jkoenig134 commented on packages/identity_recovery_kit/example/lib/main.dart
> +            ),
we talked about having way more stuff to setup (headerTitle, ...) in general **everything** that can be configured should be able to configure.

2024-11-26 12:14 UTC, jkoenig134 commented on packages/identity_recovery_kit/example/lib/main.dart
> +const id = 'did:e:nmshd-bkb.meinbildungsraum.de:dids:4fe203de633a66b56730e3';
why do you call this ID, when this is **obviously** an address?

2024-11-26 12:14 UTC, jkoenig134 commented on packages/identity_recovery_kit/example/lib/main.dart
> +const needHelpText = 'Wenden Sie sich an den Mein Bildungsraum-Support: support@meinbildungsraum.de';
hardcoded stuff has to be english. And pls remove Bildungsraum mentions

2024-11-26 12:14 UTC, jkoenig134 commented on packages/identity_recovery_kit/lib/src/pdf_generator.dart
> +  }
why isn't this in another file?

2024-11-26 12:14 UTC, jkoenig134 commented on packages/identity_recovery_kit/lib/src/pdf_generator.dart
> +    final qrImage = pw.MemoryImage(qrCodeBytes);
why does `_generateQrCode` not return a `pw.MemoryImage`?

2024-11-26 12:14 UTC, jkoenig134 commented on TODO.txt
???

2024-11-28 10:54 UTC, jkoenig134 commented on packages/identity_recovery_kit/README.md
> +# identity recovery kit
```suggestion
# Identity Recovery Kit Generator
```

2024-11-28 14:00 UTC, jkoenig134 approved these changes

2024-11-28 14:00 UTC, merged